INSERT INTO MUSEUM (id, IMAGE_PATH, location, name, AVAILABLE_QUANTITY, PRICE, DESCRIPTION)
VALUES (default, 'images/prado.jpeg', 'Madrid', 'Prado', 10, 10, 'The Prado Museum, officially known as Museo Nacional del Prado, is the main Spanish national art museum, located in central Madrid. It is widely considered to house one of the world''s finest collections of European art, dating from the 12th century to the early 20th century, based on the former Spanish royal collection, and the single best collection of Spanish art.'),
       (default, 'images/louvre.jpeg', 'Paris', 'Louvre', 10, 10, 'The Louvre, or the Louvre Museum, is the world''s most-visited museum, and a historic landmark in Paris, France. It is the home of some of the best-known works of art, including the Mona Lisa and the Venus de Milo.'),
       (default, 'images/britishMuseum.jpeg', 'London', 'British Museum', 10, 10, 'The British Museum is a public museum dedicated to human history, art and culture located in the Bloomsbury area of London. Its permanent collection of eight million works is among the largest and most comprehensive in existence. It documents the story of human culture from its beginnings to the present.'),
       (default, 'images/nationalGallery.jpeg', 'London', 'National Gallery', 10, 10, 'The National Gallery is an art museum in Trafalgar Square in the City of Westminster, in Central London, England. Founded in 1824, in Trafalgar Square since 1838, it houses a collection of over 2,300 paintings dating from the mid-13th century to 1900.'),
       (default, 'images/accademia.jpeg', 'Florence', 'Accademia', 10, 10, 'The Accademia Gallery of Venice is an essential visit for painting enthusiasts; it is the most important museum that you can visit during your stay in Venice. The Academy was intended to bring together under one roof all the works of art that were scattered throughout Venice.'),
       (default, 'images/stPeter.jpeg', 'Vatican City', 'St Peters Basilica', 10, 10, 'The Papal Basilica of Saint Peter in the Vatican, or simply Saint Peter''s Basilica, is a church built in the Renaissance style located in Vatican City, the papal enclave that is within the city of Rome, Italy.'),
       (default, 'images/sistine.jpeg', 'Vatican City', 'Sistine Chapel', 10, 10, 'The Sistine Chapel is a chapel in the Apostolic Palace, the official residence of the pope in Vatican City. Originally known as the Cappella Magna, the chapel takes its name from Pope Sixtus IV, who had it built between 1473 and 1481'),
       (default, 'images/vanGoghMuseum.jpeg', 'Amsterdam', 'Van Gogh Museum', 10, 10, 'The Van Gogh Museum is a Dutch art museum dedicated to the works of Vincent van Gogh and his contemporaries in the Museum Square in Amsterdam South, close to the Stedelijk Museum, the Rijksmuseum, and the Concertgebouw.'),
       (default, 'images/nationalHistory.jpeg', 'New York', 'American Museum of Natural History', 10, 10, 'The American Museum of Natural History is a natural history museum on the Upper West Side of Manhattan in New York City. The Museum is renowned for its exhibitions and scientific collections, which serve as a field guide to the entire planet and present a panorama of the world''s cultures.'),
       (default, 'images/smithsonian.jpeg', 'Washington D.C.', 'Smithsonian National Museum of American History', 10, 10, 'The National Museum of American History: Kenneth E. Behring Center collects, preserves, and displays the heritage of the United States in the areas of social, political, cultural, scientific, and military history. Among the items on display is the original Star-Spangled Banner.'),
       (default, 'images/tateModern.jpeg', 'London', 'Tate Modern', 10, 10, 'Tate is an institution that houses, in a network of four art galleries, the United Kingdom''s national collection of British art, and international modern and contemporary art. It is not a government institution, but its main sponsor is the UK Department for Digital, Culture, Media and Sport'),
       (default, 'images/uffizi.jpeg', 'Florence', 'Uffizi Gallery', 10, 10, 'The Uffizi Gallery entirely occupies the first and second floors of the large building constructed between 1560 and 1580 and designed by Giorgio Vasari. It is famous worldwide for its outstanding collections of ancient sculptures and paintings (from the Middle Ages to the Modern period).'),
       (default, 'images/hermitage.jpeg', 'St Petersburg', 'Hermitage Museum', 10, 10, 'The State Hermitage Museum is a museum of art and culture in Saint Petersburg, Russia. It is the largest art museum in the world by gallery space. It was founded in 1764 when Empress Catherine the Great acquired an impressive collection of paintings from the Berlin merchant Johann Ernst Gotzkowsky'),
       (default, 'images/rijksmuseum.jpeg', 'Amsterdam', 'Rijksmuseum', 10, 10, 'The Rijksmuseum is the national museum of the Netherlands dedicated to Dutch arts and history and is located in Amsterdam. The museum is located at the Museum Square in the borough of Amsterdam South, close to the Van Gogh Museum, the Stedelijk Museum Amsterdam, and the Concertgebouw.'),
       (default, 'images/dOrsay.jpeg', 'Paris', 'Musée dOrsay', 10, 10, 'The Musée d''Orsay is a museum in Paris, France, on the Left Bank of the Seine. It is housed in the former Gare d''Orsay, a Beaux-Arts railway station built between 1898 and 1900. The museum holds mainly French art dating from 1848 to 1914, including paintings, sculptures, furniture, and photography.'),
       (default, 'images/moma.jpeg', 'New York', 'Museum of Modern Art', 10, 10, 'The Museum of Modern Art is an art museum located in Midtown Manhattan, New York City, on 53rd Street between Fifth and Sixth Avenues. It plays a major role in developing and collecting modern art, and is often identified as one of the largest and most influential museums of modern art in the world.'),
       (default, 'images/nmok.jpeg', 'Seoul', 'National Museum of Korea', 10, 10, 'The National Museum of Korea is the flagship museum of Korean history and art in South Korea and is the cultural organization that represents Korea. The museum holds an immense collection: it has more than 310,000 historically valuable and highly aesthetic relics ranging from the Paleolithic Age to the early 20th century, and more than 12,000 masterpieces of its collection are always on display in its permanent exhibition hall.'),
       (default, 'images/pergamon.jpeg', 'Berlin', 'Pergamon Museum', 10, 10, 'The Pergamon Museum is a listed building on the Museum Island in the historic centre of Berlin. It was built from 1910 to 1930 by order of German Emperor Wilhelm II according to plans by Alfred Messel and Ludwig Hoffmann in Stripped Classicism style.');

INSERT INTO ARTIST (id, name, birthplace, birth_year, ARTIST_URL)
VALUES (default, 'Michelangelo', 'Italy', 1475, 'michelangelo'),
       (default, 'Rodin', 'France', 1840, 'auguste-rodin'),
       (default, 'Donatello', 'Italy', 1386, 'donatello'),
       (default, 'VanGogh', 'Netherlands', 1853, 'vincent-van-gogh'),
       (default, 'Picasso', 'Spain', 1881, 'pablo-picasso'),
       (default, 'daVinci', 'Italy', 1452, 'leonardo-da-vinci'),
       (default, 'Rembrandt', 'Netherlands', 1606, 'rembrandt'),
       (default, 'Monet', 'France', 1840, 'claude-monet'),
       (default, 'Dali', 'Spain', 1904, 'salvador-dali'),
       (default, 'Warhol', 'United States', 1928, 'andy-warhol'),
       (default, 'Vermeer', 'Netherlands', 1632, 'johannes-vermeer'),
       (default, 'Raphael', 'Italy', 1483, 'raphael'),
       (default, 'Gauguin', 'France', 1848, 'paul-gauguin'),
       (default, 'Titian', 'Italy', 1488, 'titian'),
       (default, 'Munch', 'Norway', 1863, 'edvard-munch'),
       (default, 'Matisse', 'France', 1869, 'henri-matisse'),
       (default, 'Renoir', 'France', 1841, 'pierre-auguste-renoir'),
       (default, 'OKeeffe', 'United States', 1887, 'georgia-o-keeffe'),
       (default, 'Klimt', 'Austria', 1862, 'gustav-klimt'),
       (default, 'Cezanne', 'France', 1839, 'paul-cezanne'),
       (default, 'Pollock', 'United States', 1912, 'jackson-pollock');

INSERT INTO SCULPTURE (id, name, sculpture_year, sculpture_price, artist_id, museum_id, IMAGE_PATH, DESCRIPTION, LINK)
VALUES (default, 'David', 1501, 100, select id from artist where name = 'Michelangelo', select id from museum where
        name = 'Accademia', 'images/sculptures/David.jpg',
        'David is a masterpiece of Renaissance sculpture, created in marble between 1501 and 1504 by the Italian artist Michelangelo. David is a 5.17-metre marble statue of the Biblical figure David, a favoured subject in the art of Florence.',
        'https://en.wikipedia.org/wiki/David_(Michelangelo)'),
       (default, 'Woman Aflame', 1980, 4.7, (select id from artist where name = 'Dali'),
        (select id from museum where name = 'Museum of Modern Art'), 'images/sculptures/Woman Aflame.jpg',
        'This sculpture unites two of Dalí’s obsessions: fire, and a female figure with drawers. The flames seem to have a life of their own, and represent the hidden intensity of unconscious desire, while the drawers represent the mystery of hidden secrets. This beautiful faceless woman symbolizes all women. For Dali, a woman’s mystery is her true beauty.',
        'https://www.daliparis.com/en/gallery-item/woman-aflame/'),
       (default, 'Dying Slave', 1516, 1.5, select id from artist where name = 'Michelangelo', select id from museum
        where name = 'Louvre', 'images/sculptures/Dying Slave.jpg',
        'The Dying Slave is a sculpture by the Italian Renaissance artist Michelangelo. Created between 1513 and 1516, it was to serve with another figure, the Rebellious Slave, at the tomb of Pope Julius II. It is a marble figure 2.15 metres in height, and is held at the Louvre, Paris.',
        'https://en.wikipedia.org/wiki/Dying_Slave'),
       (default, 'Thinker', 1904, 80, select id from artist where name = 'Rodin', select id from museum where name =
        'Louvre', 'images/sculptures/Thinker.jpg',
        'The Thinker is a bronze sculpture by Auguste Rodin, usually placed on a stone pedestal. The work depicts a nude male figure of heroic size sitting on a rock. He is seen leaning over, his right elbow placed on his left thigh, holding the weight of his chin on the back of his right hand.',
        'https://en.wikipedia.org/wiki/The_Thinker'),
       (default, 'Saint Mark', 1411, 7.5, select id from artist where name = 'Donatello', select id from museum where
        name = 'Louvre', 'images/sculptures/Saint Mark.jpg',
        'Donatello''s Saint Mark is a marble statue that stands approximately seven feet and nine inches high and is displayed in the museum of the Orsanmichele church, Florence. It originally was displayed in an exterior niche of the church, where a copy now stands.',
        'https://en.wikipedia.org/wiki/Saint_Mark_(Donatello)'),
       (default, 'Pieta', 1499, 5, select id from artist where name = 'Michelangelo', select id from museum where name =
        'St Peters Basilica', 'images/sculptures/Pieta.jpg',
        'The Pietà is a subject in Christian art depicting the Blessed Virgin Mary cradling the mortal body of Jesus Christ after his Descent from the Cross. It is most often found in sculpture.',
        'https://en.wikipedia.org/wiki/Piet%C3%A0'),
       (default, 'Bacchus', 1497, 4.5, (select id from artist where name = 'Michelangelo'),
        (select id from museum where name = 'Sistine Chapel'), 'images/sculptures/Bacchus.jpg',
        'In ancient Greek religion and myth, Dionysus (/daɪ.əˈnaɪsəs/; Ancient Greek: Διόνυσος Dionysos) is the god of the grape-harvest, winemaking, orchards and fruit, vegetation, fertility, festivity, insanity, ritual madness, religious ecstasy, and theatre.[2][3] The Romans called him Bacchus (/ˈbækəs/ or /ˈbɑːkəs/; Ancient Greek: Βάκχος Bacchos)[4] for a frenzy he is said to induce called baccheia. ',
        'https://en.wikipedia.org/wiki/Dionysus'),
       (default, 'Brillo Boxes', 1964, 1.8, (select id from artist where name = 'Warhol'),
        (select id from museum where name = 'Smithsonian National Museum of American History'),
        'images/sculptures/Brillo Boxes.PNG',
        'Andy Warhol''s Brillo Boxes are precise copies of commercial packaging. While they fulfill the idea that art should imitate life, they also raise questions about how we identify and value something as art. If Warhol transformed a mundane commercial product into a work of art, how did that transformation happen?',
        'https://philamuseum.org/collection/object/89204#:~:text=Andy%20Warhol''s%20Brillo%20Boxes%20are,how%20did%20that%20transformation%20happen%3F');

INSERT INTO PAINTING (id, IMAGE_PATH, name, painting_price, painting_year, museum_id, artist_id, LINK, DESCRIPTION)
VALUES (default, 'images/paintings/The Starry Night.jpg', 'The Starry Night', 117, 1890, SELECT id FROM museum WHERE
        name = 'Museum of Modern Art', SELECT id FROM artist WHERE name = 'VanGogh',
        'https://en.wikipedia.org/wiki/The_Starry_Night',
        'The Starry Night is an oil-on-canvas painting by the Dutch Post-Impressionist painter Vincent van Gogh. Painted in June 1889, it depicts the view from the east-facing window of his asylum room at Saint-Rémy-de-Provence, just before sunrise, with the addition of an imaginary village'),
       (default, 'images/paintings/The Kiss.jpeg', 'The Kiss', 5.5, 1908, SELECT id from museum where name =
        'Musée dOrsay', SELECT id from artist where name = 'Klimt',
        'https://en.wikipedia.org/wiki/The_Kiss_%28Klimt%29',
        'The Kiss is an oil-on-canvas painting with added gold leaf, silver and platinum by the Austrian Symbolist painter Gustav Klimt. It was painted at some point in 1907 and 1908, during the height of what scholars call his "Golden Period".'),
       (default, 'images/paintings/The Creation of Adam.jpg', 'The Creation of Adam', 80, 1512,
           SELECT id from museum where name = 'Sistine Chapel', select id from artist where name = 'Michelangelo',
        'https://en.wikipedia.org/wiki/The_Creation_of_Adam',
        'The Creation of Adam is a fresco painting by Italian artist Michelangelo, which forms part of the Sistine Chapel''s ceiling, painted c. 1508–1512. It illustrates the Biblical creation narrative from the Book of Genesis in which God gives life to Adam, the first man.'),
       (default, 'images/paintings/Wheatfield with Crows.jpeg', 'Wheatfield with Crows', 117, 1890,
           SELECT id from museum where name = 'Van Gogh Museum', select id from artist where name = 'VanGogh',
        'https://en.wikipedia.org/wiki/Wheatfield_with_Crows',
        'Wheatfield with Crows is a July 1890 painting by Vincent van Gogh. It has been cited by several critics as one of his greatest works. It is commonly stated that this was van Gogh''s final painting because Vincente Minnelli’s 1956 biopic “Lust for Life” depicts van Gogh painting it shortly before killing himself.'),
       (default, 'images/paintings/Mona Lisa.jpeg', 'Mona Lisa', 870, 1517,
           SELECT id from museum where name = 'Louvre', select id from artist where name = 'daVinci',
        'https://en.wikipedia.org/wiki/Mona_Lisa',
        'The Mona Lisa is a half-length portrait painting by Italian artist Leonardo da Vinci. Considered an archetypal masterpiece of the Italian Renaissance, it has been described as "the best known, the most visited, the most written about, the most sung about, the most parodied work of art in the world".'),
       (default, 'images/paintings/The Scream.jpg', 'The Scream', 100, 1888,
           SELECT id FROM museum WHERE name = 'National Gallery', SELECT id FROM artist WHERE name = 'Munch',
        'https://en.wikipedia.org/wiki/The_Scream',
        'The Scream is a composition created by Norwegian artist Edvard Munch in 1893. The agonized face in the painting has become one of the most iconic images of art, seen as symbolizing the anxiety of the human condition.'),
       (default, 'images/paintings/Les femmes dAlger.jpg', 'Les femmes dAlger', 10, 1954,
           SELECT id FROM museum WHERE name = 'Louvre', SELECT id FROM artist WHERE name = 'Picasso',
        'https://en.wikipedia.org/wiki/Les_Femmes_dAlger',
        'Les Femmes d''Alger is a series of 15 paintings and numerous drawings by the Spanish artist Pablo Picasso. The series, created in 1954–1955, was inspired by Eugène Delacroix''s 1834 painting The Women of Algiers in their Apartment. The series is one of several painted by Picasso in tribute to artists that he admired.'),
       (default, 'images/paintings/Prophet Isaiah.jpg', 'Prophet Isaiah', 80, 1512,
           SELECT id FROM museum WHERE name = 'Sistine Chapel', SELECT id FROM artist WHERE name = 'Michelangelo',
        'https://en.wikipedia.org/wiki/Les_Femmes_dAlger',
        'The Prophet Isaiah is one of the seven Old Testament prophets painted by the Italian High Renaissance master Michelangelo on the Sistine Chapel ceiling. The Sistine Chapel is in Vatican Palace, in the Vatican City.'),
       (default, 'images/paintings/The Deluge.jpg', 'The Deluge', 870, 1512,
           SELECT id FROM museum WHERE name = 'Sistine Chapel', SELECT id FROM artist WHERE name = 'Michelangelo',
        'https://en.wikipedia.org/wiki/Sistine_Chapel',
        'Michelangelo''s Deluge sits at the heart of the masterwork which is the ceiling of the Sistine Chapel. Comprising thirty three different panels in all, it is the central section of nine panels, depicting the story of Genesis which lie at the heart of the ceiling; and which could be considered Michelangelo''s masterwork.'),
       (default, 'images/paintings/The Temptation of St. Anthony.jpg', 'The Temptation of St. Anthony', 125, 1946,
           SELECT id FROM museum WHERE name = 'Museum of Modern Art', SELECT id FROM artist WHERE name = 'Dali',
        'https://en.wikipedia.org/wiki/The_Temptation_of_St._Anthony_(Dal%C3%AD)',
        'The Temptation of St. Anthony is a painting by Spanish surrealist artist Salvador Dalí. Painted in 1946, it is a precursor to the body of Dalí''s work commonly known as the "classical period" or the "Dalí Renaissance".'),
       (default, 'images/paintings/The Persistence of Memory.jpg', 'The Persistence of Memory', 110, 1931,
           SELECT id FROM museum WHERE name = 'Museum of Modern Art', SELECT id FROM artist WHERE name = 'Dali',
        'https://en.wikipedia.org/wiki/The_Persistence_of_Memory',
        'The Persistence of Memory is a 1931 painting by artist Salvador Dalí and one of the most recognizable works of Surrealism. First shown at the Julien Levy Gallery in 1932, since 1934 the painting has been in the collection of the Museum of Modern Art in New York City, which received it from an anonymous donor.'),
       (default, 'images/paintings/Night Watch.jpg', 'Night Watch', 140, 1642,
           SELECT id FROM museum WHERE name = 'Rijksmuseum', SELECT id FROM artist WHERE name = 'Rembrandt',
        'https://en.wikipedia.org/wiki/The_Night_Watch',
        'Militia Company of District II under the Command of Captain Frans Banninck Cocq, also known as The Shooting Company of Frans Banning Cocq and Willem van Ruytenburch, but commonly referred to as The Night Watch, is a 1642 painting by Rembrandt van Rijn. '),
       (default, 'images/paintings/sunflowers.jpeg', 'Sunflowers', 100, 1888,
           SELECT id FROM museum WHERE name = 'Van Gogh Museum', SELECT id FROM artist WHERE name = 'VanGogh',
        'https://en.wikipedia.org/wiki/Sunflowers_(Van_Gogh_series)',
        'Sunflowers is the title of two series of still life paintings by the Dutch painter Vincent van Gogh. The first series, executed in Paris in 1887, depicts the flowers lying on the ground, while the second set, made a year later in Arles, shows a bouquet of sunflowers in a vase.'),
       (default, 'images/paintings/Buste de femme.jpg', 'Buste de femme', 10, 1943,
           SELECT id FROM museum WHERE name = 'Louvre', SELECT id FROM artist WHERE name = 'Picasso',
        'https://en.wikipedia.org/wiki/File:Pablo_Picasso,_1909,_Buste_de_femme,_Femme_en_vert,_Femme_assise,_oil_on_canvas,_100.3_x_81.3_cm,_Van_Abbemuseum,_Netherlands.jpg',
        'Pablo Picasso painted Buste de femme (Femme à la résille) on 12 January 1938, at the height of his relationship with the photographer Dora Maar. This picture is one of the best-known of his series of images of Dora, and crucially one of the best known remaining in private hands.'),
       (default, 'images/paintings/The School of Athens.png', 'The School of Athens', 160, 1510,
           SELECT id FROM museum WHERE name = 'Sistine Chapel', SELECT id FROM artist WHERE name = 'Raphael',
        'https://en.wikipedia.org/wiki/The_School_of_Athens',
        'The School of Athens is a fresco by the Italian Renaissance artist Raphael. The fresco was painted between 1509 and 1511 as a part of Raphael''s commission to decorate the rooms now known as the Stanze di Raffaello, in the Apostolic Palace in the Vatican.');


INSERT INTO CUSTOMER VALUES (1,'peter.smith@gmail.com','Peter Smith','peter');
INSERT INTO CUSTOMER VALUES (2,'helen.stewart@gmail.com', 'Helen Stewart','helen');
INSERT INTO CUSTOMER VALUES (3,'nicole.jackson@gmail.com', 'Nicole Jackson','nicole');
INSERT INTO CUSTOMER VALUES (4,'richard.gibson@gmail.com','Richard Gibson', 'richard');



